server:
  port: 8081

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10     # ??? ???? ??
    lease-expiration-duration-in-seconds: 30  # ??? ??? ?? ??
    prefer-ip-address: true                   # ? ??? ??? ? Hostname ?? IP ?? ????
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    register-with-eureka: true # ?? ??? IP??? ???? ??
    fetch-registry: true       # ???? ??? ???? ???? ?

spring:
  application:
    name: board-command

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MASTER_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      com.example.demo: debug
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace